

CREATE TABLE [Asistencia] (
	[Id]	INTEGER NOT NULL UNIQUE,
	[Fecha]	TEXT NOT NULL DEFAULT CURRENT_DATE,
	[Llegada]	TEXT NOT NULL DEFAULT CURRENT_TIME,
	[Salida]	TEXT NOT NULL DEFAULT '',
	PRIMARY KEY([Id] AUTOINCREMENT)
);